# -*- coding: utf-8 -*-
"""Another copy of DS_assignment-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14X5tKnrDlTjvCH0T3ULcPz0t-sirX0Z0

Print the First 3 multiples of the given number "N". (N is a positive integer)

Note: print the characters with a single space between them.

Input Description:

A positive integer is provided to you as an input.

Output Description:

Print the First 3 multiples of the number with single spaces between them as an output.

Sample Input :

2

Sample Output :

2 4 6
"""

a=2
print(a,a*2,a*3,sep=" ")



"""Get user input using input(“Enter your age: ”). If user is 18 or older, give feedback: You are old enough to drive. If below 18 give feedback to wait for the missing amount of years.

Output:
Enter your age: 30

You are old enough to learn to drive.
Output:

Enter your age: 15

You need 3 more years to learn to drive.

"""

a=int(input("enter your age"))
if a>18:
  print("you are old enough to drive")
else:
  print("you have to enough")



"""Write a code to get the input in the given format and print the output in the given format

Input Description:

Three integers are given in line by line.

Output Description:

Print the integers in a single line separate by space.

Sample Input :

2

4

5

Sample Output :

2 4 5
"""

a=input()
b=input()
c=input()
print(a,b,c,sep=",")



"""Write a code to get the input in the given format and print the output in the given format

Input Description:

First-line indicates two integers separated by space. Second-line indicates three integers separated by space. Third-line indicates three integers separated by space

Output Description:

Print the input in the same format.

Sample Input :

2 5

2 5 6

2 4 5

Sample Output :

2 5

2 5 6

2 4 5
"""

a=input()
b=input()
c=input()
print(a)
print(b)
print(c)



"""Write a code to get the input in the given format and print the output in the given format

Input Description:

First-line indicates two integers separated by space. Second-line indicates two integers separated by space. Third-line indicates two integers separated by space.

Output Description:

Print the input in the same format.

Sample Input :

2 4

2 4

2 4

Sample Output :

2 4

2 4

2 4
"""

a=input()
b=input()
c=input()
print(a)
print(b)
print(c)



"""Write a Python program to count the number of even and odd numbers in a series of numbers

Sample numbers : numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)

Expected Output :

Number of even numbers : 4

Number of odd numbers : 5
"""

numbers=[1,2,3,4,5,6,7,8,9]
print(numbers[0::2])
print(numbers[1::2])





"""Display float number with 2 decimal places using print()

input: num = 458.541315

expected output = 458.54
"""

print(round(458.541315,2))



"""Check Palindrome Number

Write a program to check if the given number is a palindrome number.

A palindrome number is a number that is the same after reverse. For example, 545, is the palindrome numbers

Expected Output:

original number 121

Yes. given number is palindrome number

original number 125

No. given number is not palindrome number
"""

a=input("enter a number:")
rev_string=a[::-1]
if a==rev_string:
  print("palindrome")
else:
  print("not palindrome")



"""Take a variable ‘age’ which is of positive value and check the following:

(a) If the age is less than 10, print “Children”.

(b) If the age is more than 60, print ‘senior citizens’

© If it is between 10 and 60, print ‘normal citizen’
"""

age=16

if age<10 and age>60 :
  print("children")
else:
  print("normal citizen")

"""Write a code to get the input in the given format and print the output in the given format.

Input Description:

A single line contains a string.

Output Description:

Print the characters in a string separated by comma.

Sample Input :

Medha

Sample Output :

M,e,d,h,a
"""

a="Medha"
print(*a,sep=",")



"""Python program to add two numbers.

num1 = 18

num2 = 7
"""

num1=18
num2=7
print(num1+num2)





""" Python program to check if a string is palindrome or not.

 mystr = “malayalam”
"""

string=input("enter a string:")
rev_string=string[::-1]
if string ==rev_string:
  print("palindrome")
else:
  print("not palindrome")



"""Python Program to calculate the square root

Note: change this value for a different result

num = 8

"""

num=8
print(8*0.5)



"""# Find square root of real or complex numbers

# Importing the complex math module

hint: import cmath

num = 1+2j
"""

import cmath
num=1+2j
sqrt=cmath.sqrt(num)
print(sqrt)







"""# Python program to swap two variables

x = 5

y = 10
"""

x=5
y=10
x,y=y,x
print(x,y)



"""Write a Python program to find out what version of Python you are using."""

import sys

print(sys.version)



"""Write a Python program to display the current date and time.

Sample Output :

Current date and time :
"""

import datetime
current=datetime.datetime.now()
print("current date and time",current)



"""Write a Python program that calculates the area of a circle based on the radius entered by the user.

Python: Area of a Circle

In geometry, the area enclosed by a circle of radius r is πr2.

r = 1.1

Area = 3.8013271108436504
"""

a=3.8013271108436504
print(3.14*1.1*2)



"""Write a Python program that accepts the user's first and last name and prints them in reverse order with a space between them.


"""

a=input("enter the firstname:")
b=input("enter the lastname: ")
print(a+" "+b)



"""The Reverse Number program in Python takes a positive number as an input and then reverses the digits of the number and then prints it on the output screen. In Python, this can be achieved either by using string slicing or by using a while loop to extract and concatenate the digits in reverse order. Check out the above link for a detailed explanation and code

Input:

67884

output:

48876
"""

a="67884"#slicing operator
print(a[::-1])

a="67884" # by reverse order in negative
print(a[-1:-6:-1])

















